version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://api:3000/api/v1
    depends_on:
      - api

  api:
    image: nsai-tasker-api:latest
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/nsai_tasker
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nsai_tasker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
